version: '3.7'
services:
  trino:
    hostname: trino
    image: 'trinodb/trino:latest'
    ports:
      - '8080:8080'
    volumes:
      - ${PWD}/trino-etc:/etc/trino
    networks:
      - network


  postgres:
    container_name: postgres
    image: postgres:14.6
    networks:
      - network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superadmin
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: metadata

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    networks:
      - network
    ports:
      - 8888:8080
  hive-metastore:
    hostname: spark
    build: .
    ports:
      - '9083:9083' 
    depends_on:
      - postgres
    networks:
      - network

  minio:
    hostname: minio
    image: 'quay.io/minio/minio:latest'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server /data --console-address ":9001"
    networks:
      - network

volumes:
  minio-data:
    driver: local

networks:
  network:
    driver: bridge
